<?php

namespace Artworksit\Starter\Console;

use DateTimeImmutable;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Symfony\Component\Process\Process;

class InstallCommand extends Command
{
    private ?Filesystem $filesystem = null;

    private bool $pendingComposerScripts = false;

    /**
     * @var array<int, array<string, string|array>>
     */
    private array $pageEntries = [];

    private bool $installBlog = false;

    private bool $installCareers = false;

    private ?string $careersMode = null;

    protected $signature = "starter:install {--force : Overwrite files generated by Starter} {--dry-run : Show what would be generated without writing files} {--install-deps : Install required SEO dependencies automatically}";

    protected $description = "Scaffold website pages, routes, controller, and base Blade components.";

    public function handle(Filesystem $files): int
    {
        $this->filesystem = $files;

        $this->info("artworksit/starter: install");
        $this->newLine();

        $dryRun = (bool) $this->option("dry-run");
        $force = (bool) $this->option("force");
        $installDeps = (bool) $this->option("install-deps");

        $pagesInput = $this->ask(
            "Which static pages do you need? (comma separated, e.g., home, about, about>history, services, contact)",
            "home, about, services, contact",
        );

        $rawPages = collect(explode(",", (string) $pagesInput))
            ->map(fn(string $page) => trim($page))
            ->filter()
            ->values()
            ->all();

        [$pages, $addedHome] = $this->normalizePages($rawPages);
        $pageTree = $this->buildPageTree($pages);
        $pageEntries = $this->flattenPageTree($pageTree);
        $this->pageEntries = $pageEntries;

        $installSeo = $this->confirm(
            "Would you like to manage SEO/Meta tags via Filament?",
            false,
        );

        if ($installSeo && !$this->ensureSeoDependencies($installDeps)) {
            $this->newLine();

            return self::FAILURE;
        }

        $installBlog = $this->confirm("Include Blog module?", false);
        $this->installBlog = $installBlog;

        if ($installBlog && ! $this->ensureBlogDependencies($installDeps)) {
            $this->newLine();

            return self::FAILURE;
        }

        $installCareers = $this->confirm('Include Careers module?', false);
        $careersMode = $installCareers
            ? $this->choice('How should jobs work?', ['external', 'internal'], 'external')
            : null;
        $this->installCareers = $installCareers;
        $this->careersMode = $careersMode;

        if ($installCareers && $careersMode === 'internal' && ! $this->ensureCareersDependencies($installDeps)) {
            $this->newLine();

            return self::FAILURE;
        }

        $this->runPostComposerScripts(false);

        if ($installSeo || $installBlog || $installCareers) {
            $this->ensureFilamentPanel();
            $this->ensureFilamentTheme();
        }

        if ($installSeo || $installBlog || ($installCareers && $careersMode === 'internal')) {
            $this->ensureMediaLibrarySetup();
        }

        if ($installBlog) {
            $this->ensureTagsSetup();
        }

        $this->line("Dry run:  " . ($dryRun ? "yes" : "no"));
        $this->line("Force:    " . ($force ? "yes" : "no"));
        $this->line("SEO:      " . ($installSeo ? "yes" : "no"));
        $this->line("Blog:     " . ($installBlog ? "yes" : "no"));
        $this->line("Careers:  " . ($installCareers ? "yes" : "no"));
        $this->line("Deps:     " . ($installDeps ? "install" : "skip"));
        $this->newLine();

        if ($addedHome) {
            $this->comment("Note: added home page automatically.");
            $this->newLine();
        }

        $this->info("Pages:");
        foreach ($pageEntries as $entry) {
            $this->line(
                sprintf(
                    "  %-16s → %-14s → %s",
                    $entry["url"],
                    $entry["route_name"],
                    Str::after($entry["view_file"], "resources/views/"),
                ),
            );
        }

        $this->newLine();

        if ($dryRun) {
            $this->comment("Dry run — no files written.");
            $this->newLine();
        }

        $manifest = $this->loadManifest();
        $filesPlan = $this->buildFilesPlan(
            $manifest,
            $pageEntries,
            $force,
            $installSeo,
            $installBlog,
            $installCareers,
            $careersMode,
        );
        $planSummary = $this->summarizePlan($filesPlan);

        if ($dryRun) {
            $this->displayPlanSummary($planSummary);

            return self::SUCCESS;
        }

        $results = $this->applyPlan($files, $filesPlan);
        $this->displayPlanSummary($planSummary);
        $this->newLine();

        $this->removeWelcomeView();

        if (!empty($results["skipped"])) {
            $this->warn(
                "Some files were skipped due to conflicts. Use --force if safe to overwrite.",
            );
        }

        if (
            $installSeo &&
            array_key_exists(
                "resources/views/components/layout.blade.php",
                $results["skipped"],
            )
        ) {
            $this->warn(
                "Layout was not updated. Add <x-seo /> inside your <head> section to enable SEO tags.",
            );
        }

        if (
            $installSeo &&
            array_key_exists(
                "resources/views/components/seo.blade.php",
                $results["skipped"],
            )
        ) {
            $this->warn(
                "SEO component was not updated. Ensure resources/views/components/seo.blade.php exists.",
            );
        }

        $this->writeManifest(
            $pageEntries,
            $results["written_files"],
            $results["skipped"],
        );

        $this->ensureDatabaseSeederCalls();

        $this->seedStarterUser();

        if ($installSeo && $installBlog) {
            $this->seedBlogIndexSeo();
        }

        if ($installSeo && $installCareers) {
            $this->seedCareersIndexSeo();
        }

        if ($installSeo) {
            $this->seedStarterSeo();
        }

        $this->runPostComposerScripts(true);

        $this->info("Starter install complete.");

        return self::SUCCESS;
    }

    /**
     * @param string[] $pages
     * @return array{0: string[], 1: bool}
     */
    private function normalizePages(array $pages): array
    {
        $normalized = collect($pages)
            ->map(function (string $page): string {
                $segments = collect(explode(">", $page))
                    ->map(
                        fn(string $segment) => Str::of($segment)
                            ->kebab()
                            ->lower()
                            ->value(),
                    )
                    ->filter();

                return $segments->implode(">");
            })
            ->filter()
            ->unique()
            ->values()
            ->all();

        $addedHome = false;

        if (in_array("home", $normalized, true)) {
            $normalized = array_values(
                array_filter($normalized, fn(string $page) => $page !== "home"),
            );
        } else {
            $addedHome = true;
        }

        array_unshift($normalized, "home");

        return [$normalized, $addedHome];
    }

    /**
     * @param string[] $pages
     * @return array<string, array>
     */
    private function buildPageTree(array $pages): array
    {
        $tree = [];

        foreach ($pages as $page) {
            $segments = array_values(array_filter(explode(">", $page)));
            $node = &$tree;

            foreach ($segments as $segment) {
                if (!array_key_exists($segment, $node)) {
                    $node[$segment] = [];
                }

                $node = &$node[$segment];
            }
        }

        return $tree;
    }

    /**
     * @param array<string, array> $tree
     * @return array<int, array<string, string|array>>
     */
    private function flattenPageTree(array $tree): array
    {
        $entries = [];

        foreach ($tree as $key => $children) {
            $this->appendEntry($entries, [$key], $children);
        }

        return $entries;
    }

    /**
     * @param array<int, array<string, string|array>> $entries
     * @param string[] $segments
     * @param array<string, array> $children
     */
    private function appendEntry(
        array &$entries,
        array $segments,
        array $children,
    ): void {
        $entries[] = $this->buildEntry($segments);

        foreach ($children as $child => $grandChildren) {
            $this->appendEntry(
                $entries,
                array_merge($segments, [$child]),
                $grandChildren,
            );
        }
    }

    /**
     * @param string[] $segments
     * @return array<string, string|array>
     */
    private function buildEntry(array $segments): array
    {
        $routeName = implode(".", $segments);
        $viewSegments = $segments;

        $url = $segments[0] === "home" ? "/" : "/" . implode("/", $segments);

        $controllerMethod =
            $segments[0] === "home"
                ? "home"
                : Str::camel(implode(" ", $segments));

        return [
            "key" => $routeName,
            "segments" => $segments,
            "url" => $url,
            "route_name" => $routeName,
            "view" => "pages." . implode(".", $viewSegments),
            "view_file" =>
                "resources/views/pages/" .
                implode("/", $viewSegments) .
                ".blade.php",
            "controller_method" => $controllerMethod,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function loadManifest(): array
    {
        $filesystem = $this->filesystem();
        $manifestPath = $this->manifestPath();

        if (!$filesystem->exists($manifestPath)) {
            return [];
        }

        $contents = $filesystem->get($manifestPath);
        $decoded = json_decode($contents, true);

        return is_array($decoded) ? $decoded : [];
    }

    /**
     * @param array<int, array<string, string|array>> $pageEntries
     * @return array<int, array<string, string>>
     */
    private function buildFilesPlan(
        array $manifest,
        array $pageEntries,
        bool $force,
        bool $installSeo,
        bool $installBlog,
        bool $installCareers,
        ?string $careersMode,
    ): array {
        $plan = [];
        $filesystem = $this->filesystem();

        $filesToGenerate = $this->generateFilesPayload(
            $pageEntries,
            $installSeo,
            $installBlog,
            $installCareers,
            $careersMode,
        );

        foreach ($filesToGenerate as $relativePath => $payload) {
            $plan[] = $this->planFile(
                $filesystem,
                $manifest,
                $relativePath,
                $payload["contents"],
                $force,
                $payload["allow_marker"] ?? false,
                $payload["always_write"] ?? false,
            );
        }

        return $plan;
    }

    /**
     * @param array<int, array<string, string|array>> $pageEntries
     * @return array<string, array{contents: string, allow_marker?: bool, always_write?: bool}>
     */
    private function generateFilesPayload(
        array $pageEntries,
        bool $installSeo,
        bool $installBlog,
        bool $installCareers,
        ?string $careersMode,
    ): array {
        $this->installBlog = $installBlog;
        $this->installCareers = $installCareers;
        $this->careersMode = $careersMode;
        $routes = collect($pageEntries)
            ->map(
                fn(array $entry) => sprintf(
                    "Route::get('%s', [WebsiteController::class, '%s'])->name('%s');",
                    $entry["url"],
                    $entry["controller_method"],
                    $entry["route_name"],
                ),
            )
            ->implode("\n");

        if ($this->installBlog) {
            $routes .= "\n\nrequire __DIR__.'/blog.php';";
        }

        if ($this->installCareers) {
            $routes .= "\n\nrequire __DIR__.'/careers.php';";
        }

        $routesStub = $this->stubPath("routes/starter.stub");
        $routesContents = $this->renderStub($routesStub, [
            "routes" => $routes,
        ]);

        $controllerMethods = collect($pageEntries)
            ->map(function (array $entry): string {
                return sprintf(
                    "    public function %s(): \\Illuminate\\View\\View\n    {\n        return view('%s');\n    }",
                    $entry["controller_method"],
                    $entry["view"],
                );
            })
            ->implode("\n\n");

        $controllerContents = $this->renderStub(
            $this->stubPath("controllers/WebsiteController.stub"),
            [
                "methods" => $controllerMethods,
            ],
        );

        $layoutContents = $this->renderStub(
            $this->stubPath("views/components/layout.stub"),
            [
                "slot" => '{{ $slot }}',
                "seo" => $installSeo ? "<x-seo />" : "<title>Starter</title>",
            ],
        );

        $headerContents = $this->renderStub(
            $this->stubPath("views/components/header.stub"),
            [
                "links" => $this->headerLinksMarkup($pageEntries, $installCareers),
            ],
        );

        $footerContents = $this->renderStub(
            $this->stubPath("views/components/footer.stub"),
            [
                "footerText" => "© " . date("Y") . " Starter",
            ],
        );

        $pageStub = $this->stubPath("views/pages/page.stub");
        $pageFiles = [];

        foreach ($pageEntries as $entry) {
            $pageFiles[$entry["view_file"]] = [
                "contents" => $this->renderStub($pageStub, [
                    "title" => Str::headline(
                        str_replace(".", " ", $entry["key"]),
                    ),
                ]),
            ];
        }

        $seoFiles = $installSeo ? $this->seoFilesPayload($layoutContents) : [];
        $blogFiles = $installBlog ? $this->blogFilesPayload() : [];
        $careersFiles = $installCareers ? $this->careersFilesPayload($careersMode) : [];

        $payload = [
            "routes/starter.php" => [
                "contents" => $routesContents,
                "allow_marker" => true,
            ],
            "routes/web.php" => [
                "contents" => $this->updateRoutesWebContents("routes/web.php"),
                "allow_marker" => false,
                "always_write" => true,
            ],
            "app/Http/Controllers/WebsiteController.php" => [
                "contents" => $controllerContents,
                "allow_marker" => true,
            ],
            "resources/views/components/layout.blade.php" => [
                "contents" => $layoutContents,
                "allow_marker" => true,
            ],
            "resources/views/components/header.blade.php" => [
                "contents" => $headerContents,
                "allow_marker" => true,
            ],
            "resources/views/components/footer.blade.php" => [
                "contents" => $footerContents,
                "allow_marker" => true,
            ],
        ];

        $extras = array_merge($seoFiles, $blogFiles, $careersFiles);

        return array_merge($payload, $extras, $pageFiles);
    }

    private function updateRoutesWebContents(string $relativePath): string
    {
        $path = base_path($relativePath);
        $filesystem = $this->filesystem();
        $contents = $filesystem->exists($path)
            ? $filesystem->get($path)
            : "<?php\n";

        $contents = $this->removeDefaultWebRoute($contents);

        if (Str::contains($contents, "require __DIR__.'/starter.php';")) {
            return $contents;
        }

        $trimmed = rtrim($contents);

        return $trimmed . "\n\nrequire __DIR__.'/starter.php';\n";
    }

    private function removeDefaultWebRoute(string $contents): string
    {
        $pattern = "/Route::get\('\/',\s*function\s*\(\)\s*\{\s*return\s+view\('welcome'\);\s*\}\);/s";

        $updated = preg_replace($pattern, '', $contents);

        if (! is_string($updated)) {
            return $contents;
        }

        $updated = str_replace("use Illuminate\\Support\\Facades\\Route;\n\n\n", "use Illuminate\\Support\\Facades\\Route;\n\n", $updated);

        return trim($updated)."\n";
    }

    private function removeWelcomeView(): void
    {
        $path = resource_path('views/welcome.blade.php');
        $filesystem = $this->filesystem();

        if (! $filesystem->exists($path)) {
            return;
        }

        $filesystem->delete($path);
        $this->line('Removed default resources/views/welcome.blade.php');
    }

    /**
     * @param array<int, array<string, string|array>> $pageEntries
     */
    private function headerLinksMarkup(array $pageEntries, bool $installCareers): string
    {
        $links = [];

        foreach ($pageEntries as $entry) {
            $links[] = sprintf(
                '<a href="%s">%s</a>',
                $entry['url'],
                Str::headline(str_replace('.', ' ', $entry['key'])),
            );
        }

        if ($this->installBlog) {
            $links[] = "@if (Route::has('blog.index'))\n            <a href=\"{{ route('blog.index') }}\">Blog</a>\n        @endif";
        }

        if ($installCareers) {
            $links[] = "@if (Route::has('careers.index'))\n            <a href=\"{{ route('careers.index') }}\">Careers</a>\n        @endif";
        }

        return implode("\n        ", $links);
    }

    /**
     * @param array<int, array<string, string|array>> $pageEntries
     */
    private function starterSeoSeederEntries(array $pageEntries): string
    {
        $entries = [];

        foreach ($pageEntries as $entry) {
            $entries[] = sprintf(
                "            [\n                'url' => '%s',\n                'meta_title' => '%s',\n                'meta_description' => '%s',\n                // 'og_image' => public_path('%s'),\n                'meta_structure' => %s,\n            ],",
                $entry['url'],
                Str::headline(str_replace('.', ' ', $entry['key'])),
                $this->starterSeoDescription($entry),
                $this->starterSeoOgImagePath($entry['url']),
                $this->starterSeoSchema($entry),
            );
        }

        return implode("\n", $entries);
    }

    /**
     * @param array<string, string|array> $entry
     */
    private function starterSeoDescription(array $entry): string
    {
        $title = Str::headline(str_replace('.', ' ', $entry['key']));

        return $title.' page generated by Starter.';
    }

    /**
     * @param array<string, string|array> $entry
     */
    private function starterSeoSchema(array $entry): string
    {
        $title = Str::headline(str_replace('.', ' ', $entry['key']));
        $schema = [
            '@context' => 'https://schema.org',
            '@type' => 'WebPage',
            'name' => $title,
            'url' => $entry['url'],
        ];

        $schemaJson = json_encode($schema, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);

        if ($schemaJson === false) {
            return '[]';
        }

        return var_export([$schemaJson], true);
    }

    private function starterSeoOgImagePath(string $url): string
    {
        $path = trim($url, '/');

        if ($path === '') {
            $path = 'home';
        }

        $path = Str::slug(str_replace('/', '-', $path));

        return 'og/'.$path.'.png';
    }

    /**
     * @return array<string, array{contents: string, allow_marker?: bool, always_write?: bool}>
     */
    private function seoFilesPayload(string $layoutContents): array
    {
        $seoMigrationContents = $this->renderStub(
            $this->stubPath("seo/migration.stub"),
            [],
        );

        $seoModelContents = $this->renderStub(
            $this->stubPath("seo/model.stub"),
            [],
        );

        $seoResourceContents = $this->renderStub(
            $this->stubPath("seo/resource.stub"),
            [],
        );

        $seoListContents = $this->renderStub(
            $this->stubPath("seo/pages/ListSiteSeos.stub"),
            [],
        );

        $seoCreateContents = $this->renderStub(
            $this->stubPath("seo/pages/CreateSiteSeo.stub"),
            [],
        );

        $seoEditContents = $this->renderStub(
            $this->stubPath("seo/pages/EditSiteSeo.stub"),
            [],
        );

        $seoComponentContents = $this->renderStub(
            $this->stubPath("seo/seo-component.stub"),
            [],
        );

        $starterSeederContents = $this->renderStub(
            $this->stubPath("seeders/StarterUserSeeder.stub"),
            [],
        );

        $seoSeederContents = $this->renderStub(
            $this->stubPath('seeders/StarterSeoSeeder.stub'),
            [
                'entries' => $this->starterSeoSeederEntries($this->pageEntries),
            ],
        );

        $migrationPath = $this->seoMigrationPath();

        return [
            $migrationPath => [
                "contents" => $seoMigrationContents,
                "allow_marker" => true,
            ],
            "app/Models/SiteSeo.php" => [
                "contents" => $seoModelContents,
                "allow_marker" => true,
            ],
            "app/Filament/Resources/SiteSeoResource.php" => [
                "contents" => $seoResourceContents,
                "allow_marker" => true,
            ],
            "app/Filament/Resources/SiteSeoResource/Pages/ListSiteSeos.php" => [
                "contents" => $seoListContents,
                "allow_marker" => true,
            ],
            "app/Filament/Resources/SiteSeoResource/Pages/CreateSiteSeo.php" => [
                "contents" => $seoCreateContents,
                "allow_marker" => true,
            ],
            "app/Filament/Resources/SiteSeoResource/Pages/EditSiteSeo.php" => [
                "contents" => $seoEditContents,
                "allow_marker" => true,
            ],
            "resources/views/components/seo.blade.php" => [
                "contents" => $seoComponentContents,
                "allow_marker" => true,
            ],
            "resources/views/components/layout.blade.php" => [
                "contents" => $layoutContents,
                "allow_marker" => true,
            ],
            "database/seeders/StarterUserSeeder.php" => [
                "contents" => $starterSeederContents,
                "allow_marker" => true,
            ],
            "database/seeders/StarterSeoSeeder.php" => [
                "contents" => $seoSeederContents,
                "allow_marker" => true,
            ],
        ];
    }

    /**
     * @return array<string, array{contents: string, allow_marker?: bool, always_write?: bool}>
     */
    private function blogFilesPayload(): array
    {
        $authorMigration = $this->renderStub(
            $this->stubPath('blog/migrations/create_blog_authors_table.stub'),
            [],
        );

        $postMigration = $this->renderStub(
            $this->stubPath('blog/migrations/create_blog_posts_table.stub'),
            [],
        );

        $authorModel = $this->renderStub(
            $this->stubPath('blog/models/BlogAuthor.stub'),
            [],
        );

        $postModel = $this->renderStub(
            $this->stubPath('blog/models/BlogPost.stub'),
            [],
        );

        $authorResource = $this->renderStub(
            $this->stubPath('blog/resources/blog-authors/resource.stub'),
            [],
        );

        $authorList = $this->renderStub(
            $this->stubPath('blog/resources/blog-authors/pages/ListBlogAuthors.stub'),
            [],
        );

        $authorCreate = $this->renderStub(
            $this->stubPath('blog/resources/blog-authors/pages/CreateBlogAuthor.stub'),
            [],
        );

        $authorEdit = $this->renderStub(
            $this->stubPath('blog/resources/blog-authors/pages/EditBlogAuthor.stub'),
            [],
        );

        $postResource = $this->renderStub(
            $this->stubPath('blog/resources/blog-posts/resource.stub'),
            [],
        );

        $postList = $this->renderStub(
            $this->stubPath('blog/resources/blog-posts/pages/ListBlogPosts.stub'),
            [],
        );

        $postCreate = $this->renderStub(
            $this->stubPath('blog/resources/blog-posts/pages/CreateBlogPost.stub'),
            [],
        );

        $postEdit = $this->renderStub(
            $this->stubPath('blog/resources/blog-posts/pages/EditBlogPost.stub'),
            [],
        );

        $blogRoutes = $this->renderStub(
            $this->stubPath('blog/routes/blog.stub'),
            [],
        );

        $blogController = $this->renderStub(
            $this->stubPath('blog/controllers/BlogController.stub'),
            [],
        );

        $blogIndex = $this->renderStub(
            $this->stubPath('blog/views/index.stub'),
            [],
        );

        $blogShow = $this->renderStub(
            $this->stubPath('blog/views/show.stub'),
            [],
        );

        $authorMigrationPath = $this->blogMigrationPath('create_blog_authors_table');
        $postMigrationPath = $this->blogMigrationPath('create_blog_posts_table');

        return [
            $authorMigrationPath => [
                'contents' => $authorMigration,
                'allow_marker' => true,
            ],
            $postMigrationPath => [
                'contents' => $postMigration,
                'allow_marker' => true,
            ],
            'app/Models/BlogAuthor.php' => [
                'contents' => $authorModel,
                'allow_marker' => true,
            ],
            'app/Models/BlogPost.php' => [
                'contents' => $postModel,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/BlogAuthorResource.php' => [
                'contents' => $authorResource,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/BlogAuthorResource/Pages/ListBlogAuthors.php' => [
                'contents' => $authorList,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/BlogAuthorResource/Pages/CreateBlogAuthor.php' => [
                'contents' => $authorCreate,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/BlogAuthorResource/Pages/EditBlogAuthor.php' => [
                'contents' => $authorEdit,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/BlogPostResource.php' => [
                'contents' => $postResource,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/BlogPostResource/Pages/ListBlogPosts.php' => [
                'contents' => $postList,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/BlogPostResource/Pages/CreateBlogPost.php' => [
                'contents' => $postCreate,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/BlogPostResource/Pages/EditBlogPost.php' => [
                'contents' => $postEdit,
                'allow_marker' => true,
            ],
            'routes/blog.php' => [
                'contents' => $blogRoutes,
                'allow_marker' => true,
            ],
            'app/Http/Controllers/BlogController.php' => [
                'contents' => $blogController,
                'allow_marker' => true,
            ],
            'resources/views/blog/index.blade.php' => [
                'contents' => $blogIndex,
                'allow_marker' => true,
            ],
            'resources/views/blog/show.blade.php' => [
                'contents' => $blogShow,
                'allow_marker' => true,
            ],
        ];
    }

    private function blogMigrationPath(string $suffix): string
    {
        $existing = glob(database_path('migrations/*_'.$suffix.'.php'));

        if (! empty($existing)) {
            return str_replace(base_path().'/', '', $existing[0]);
        }

        $timestamp = (new DateTimeImmutable())->format('Y_m_d_His');

        return 'database/migrations/'.$timestamp.'_'.$suffix.'.php';
    }

    /**
     * @return array<string, array{contents: string, allow_marker?: bool, always_write?: bool}>
     */
    private function careersFilesPayload(?string $careersMode): array
    {
        $jobMigration = $this->renderStub(
            $this->stubPath('careers/migrations/create_job_listings_table.stub'),
            [],
        );

        $jobModel = $this->renderStub(
            $this->stubPath('careers/models/JobListing.stub'),
            [],
        );

        $jobResource = $this->renderStub(
            $this->stubPath('careers/resources/job-listings/resource.stub'),
            [
                'externalLinkRequired' => $careersMode === 'external' ? "->required()" : "",
            ],
        );

        $jobList = $this->renderStub(
            $this->stubPath('careers/resources/job-listings/pages/ListJobListings.stub'),
            [],
        );

        $jobCreate = $this->renderStub(
            $this->stubPath('careers/resources/job-listings/pages/CreateJobListing.stub'),
            [],
        );

        $jobEdit = $this->renderStub(
            $this->stubPath('careers/resources/job-listings/pages/EditJobListing.stub'),
            [],
        );

        $jobRoutes = $this->renderStub(
            $this->stubPath('careers/routes/careers.stub'),
            [],
        );

        $jobController = $this->renderStub(
            $this->stubPath('careers/controllers/JobController.stub'),
            [],
        );

        $jobFactory = $this->renderStub(
            $this->stubPath('careers/factories/JobListingFactory.stub'),
            [],
        );

        $careersIndex = $this->renderStub(
            $this->stubPath('careers/views/index.stub'),
            [],
        );

        $careersShow = $this->renderStub(
            $this->stubPath('careers/views/show.stub'),
            [],
        );

        $payload = [
            $this->careersMigrationPath('create_job_listings_table') => [
                'contents' => $jobMigration,
                'allow_marker' => true,
            ],
            'app/Models/JobListing.php' => [
                'contents' => $jobModel,
                'allow_marker' => true,
            ],
            'database/factories/JobListingFactory.php' => [
                'contents' => $jobFactory,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/JobListingResource.php' => [
                'contents' => $jobResource,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/JobListingResource/Pages/ListJobListings.php' => [
                'contents' => $jobList,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/JobListingResource/Pages/CreateJobListing.php' => [
                'contents' => $jobCreate,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/JobListingResource/Pages/EditJobListing.php' => [
                'contents' => $jobEdit,
                'allow_marker' => true,
            ],
            'routes/careers.php' => [
                'contents' => $jobRoutes,
                'allow_marker' => true,
            ],
            'app/Http/Controllers/JobController.php' => [
                'contents' => $jobController,
                'allow_marker' => true,
            ],
            'resources/views/careers/index.blade.php' => [
                'contents' => $careersIndex,
                'allow_marker' => true,
            ],
            'resources/views/careers/show.blade.php' => [
                'contents' => $careersShow,
                'allow_marker' => true,
            ],
        ];

        if ($careersMode === 'internal') {
            $payload = array_merge($payload, $this->careersInternalFiles());
        }

        return $payload;
    }

    /**
     * @return array<string, array{contents: string, allow_marker?: bool, always_write?: bool}>
     */
    private function careersInternalFiles(): array
    {
        $submissionMigration = $this->renderStub(
            $this->stubPath('careers/migrations/create_job_submissions_table.stub'),
            [],
        );

        $submissionModel = $this->renderStub(
            $this->stubPath('careers/models/JobSubmission.stub'),
            [],
        );

        $submissionResource = $this->renderStub(
            $this->stubPath('careers/resources/job-submissions/resource.stub'),
            [],
        );

        $submissionList = $this->renderStub(
            $this->stubPath('careers/resources/job-submissions/pages/ListJobSubmissions.stub'),
            [],
        );

        $submissionView = $this->renderStub(
            $this->stubPath('careers/resources/job-submissions/pages/ViewJobSubmission.stub'),
            [],
        );

        $applyView = $this->renderStub(
            $this->stubPath('careers/views/apply.stub'),
            [],
        );

        $applyComponent = $this->renderStub(
            $this->stubPath('careers/livewire/ApplyJob.stub'),
            [],
        );

        $applyComponentView = $this->renderStub(
            $this->stubPath('careers/views/livewire-apply.stub'),
            [],
        );

        return [
            $this->careersMigrationPath('create_job_submissions_table') => [
                'contents' => $submissionMigration,
                'allow_marker' => true,
            ],
            'app/Models/JobSubmission.php' => [
                'contents' => $submissionModel,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/JobSubmissionResource.php' => [
                'contents' => $submissionResource,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/JobSubmissionResource/Pages/ListJobSubmissions.php' => [
                'contents' => $submissionList,
                'allow_marker' => true,
            ],
            'app/Filament/Resources/JobSubmissionResource/Pages/ViewJobSubmission.php' => [
                'contents' => $submissionView,
                'allow_marker' => true,
            ],
            'resources/views/careers/apply.blade.php' => [
                'contents' => $applyView,
                'allow_marker' => true,
            ],
            'app/Livewire/Careers/ApplyJob.php' => [
                'contents' => $applyComponent,
                'allow_marker' => true,
            ],
            'resources/views/livewire/careers/apply-job.blade.php' => [
                'contents' => $applyComponentView,
                'allow_marker' => true,
            ],
        ];
    }

    private function careersMigrationPath(string $suffix): string
    {
        $existing = glob(database_path('migrations/*_'.$suffix.'.php'));

        if (! empty($existing)) {
            return str_replace(base_path().'/', '', $existing[0]);
        }

        $timestamp = (new DateTimeImmutable())->format('Y_m_d_His');

        return 'database/migrations/'.$timestamp.'_'.$suffix.'.php';
    }

    private function seedCareersIndexSeo(): void
    {
        if (! $this->siteSeoModelExists()) {
            return;
        }

        if (! $this->confirm('Add SEO entry for /careers to StarterSeoSeeder?', true)) {
            return;
        }

        $this->addSeoSeederEntries([
            [
                'url' => '/careers',
                'meta_title' => 'Careers',
                'meta_description' => 'Careers page generated by Starter.',
            ],
        ]);
    }

    private function seedBlogIndexSeo(): void
    {
        if (! $this->siteSeoModelExists()) {
            return;
        }

        if (! $this->confirm('Add SEO entry for /blog to StarterSeoSeeder?', true)) {
            return;
        }

        $this->addSeoSeederEntries([
            [
                'url' => '/blog',
                'meta_title' => 'Blog',
                'meta_description' => 'Blog posts generated by Starter.',
                'meta_structure' => [
                    json_encode(
                        [
                            '@context' => 'https://schema.org',
                            '@type' => 'Blog',
                            'name' => 'Blog',
                            'url' => '/blog',
                        ],
                        JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT,
                    ),
                ],
            ],
        ]);
    }

    /**
     * @param array<int, array<string, mixed>> $entries
     */
    private function addSeoSeederEntries(array $entries): void
    {
        $path = $this->starterSeoSeederPath();
        $filesystem = $this->filesystem();

        if (! $filesystem->exists($path)) {
            $this->warn('StarterSeoSeeder not found. Skipping SEO entry updates.');

            return;
        }

        $contents = $filesystem->get($path);

        $contents = preg_replace(
            '/^use Illuminate\\Database\\Console\\Seeds\\WithoutModelEvents;\R/m',
            '',
            $contents,
        );
        $contents = preg_replace('/^\s*use WithoutModelEvents;\R/m', '', $contents);

        if (! Str::contains($contents, 'Generated by Starter Package')) {
            $this->warn('StarterSeoSeeder does not appear to be managed by Starter. Skipping updates.');

            return;
        }

        $newEntries = [];

        foreach ($entries as $entry) {
            $url = $entry['url'] ?? null;

            if (! is_string($url) || $url === '') {
                continue;
            }

            $pattern = '/[\'\"]url[\'\"]\s*=>\s*[\'\"]' . preg_quote($url, '/') . '[\'\"]/';

            if (preg_match($pattern, $contents) === 1) {
                continue;
            }

            $newEntries[] = $entry;
        }

        if ($newEntries === []) {
            $this->line('StarterSeoSeeder already includes these SEO entries.');

            return;
        }

        $formatted = $this->formatSeoEntries($newEntries);
        $pattern = '/(\$entries\s*=\s*\[)(.*?)(\n\s*\];)/s';

        if (! preg_match($pattern, $contents)) {
            $this->warn('Unable to locate entries array in StarterSeoSeeder. Skipping updates.');

            return;
        }

        $updated = preg_replace_callback($pattern, function (array $matches) use ($formatted): string {
            $body = rtrim($matches[2]);
            $body = $body === '' ? '' : $body . "\n";
            $body .= rtrim($formatted);

            return $matches[1] . $body . $matches[3];
        }, $contents, 1);

        if ($updated === null) {
            $this->warn('Failed to update StarterSeoSeeder.');

            return;
        }

        $filesystem->put($path, $updated);
        $this->info('StarterSeoSeeder updated with additional SEO entries.');
    }

    private function siteSeoModelExists(): bool
    {
        return $this->filesystem()->exists(app_path('Models/SiteSeo.php'));
    }

    private function ensureDatabaseSeederCalls(): void
    {
        $path = database_path('seeders/DatabaseSeeder.php');
        $filesystem = $this->filesystem();

        if (! $filesystem->exists($path)) {
            $this->warn('DatabaseSeeder not found. Skipping seeder registration.');

            return;
        }

        $contents = $filesystem->get($path);

        if (
            Str::contains($contents, 'StarterUserSeeder::class')
            && Str::contains($contents, 'StarterSeoSeeder::class')
        ) {
            return;
        }

        if (! preg_match('/^(\s*)public function run\(\): void/m', $contents, $indentMatches)) {
            $this->warn('Unable to locate DatabaseSeeder::run. Skipping seeder registration.');

            return;
        }

        $indent = $indentMatches[1] ?? '    ';
        $bodyIndent = $indent.'    ';
        $pattern = '/public function run\(\): void\s*\{(?P<body>.*?)\}/s';

        $updated = preg_replace_callback($pattern, function (array $matches) use ($bodyIndent, $indent): string {
            $body = $matches['body'];
            $needsUserSeeder = ! Str::contains($body, 'StarterUserSeeder::class');
            $needsSeoSeeder = ! Str::contains($body, 'StarterSeoSeeder::class');

            if (! $needsUserSeeder && ! $needsSeoSeeder) {
                return $matches[0];
            }

            $seeders = [];

            if ($needsUserSeeder) {
                $seeders[] = 'StarterUserSeeder::class';
            }

            if ($needsSeoSeeder) {
                $seeders[] = 'StarterSeoSeeder::class';
            }

            $callBlock = $bodyIndent.'$this->call(['."\n";

            foreach ($seeders as $seeder) {
                $callBlock .= $bodyIndent.'    '.$seeder.",\n";
            }

            $callBlock .= $bodyIndent.']);';
            $existingBody = ltrim($body, "\n");
            $newBody = $callBlock;

            if (trim($existingBody) !== '') {
                $newBody .= "\n".$existingBody;
            }

            return "public function run(): void {\n".$newBody."\n".$indent.'}';
        }, $contents, 1);

        if ($updated === null) {
            $this->warn('Failed to update DatabaseSeeder.');

            return;
        }

        $filesystem->put($path, $updated);
    }

    private function starterSeoSeederPath(): string
    {
        return database_path('seeders/StarterSeoSeeder.php');
    }

    /**
     * @param array<int, array<string, mixed>> $entries
     */
    private function formatSeoEntries(array $entries): string
    {
        $lines = [];

        foreach ($entries as $entry) {
            $lines[] = $this->formatSeoEntry($entry);
        }

        return implode("\n", $lines);
    }

    /**
     * @param array<string, mixed> $entry
     */
    private function formatSeoEntry(array $entry): string
    {
        $schema = $entry['meta_structure'] ?? null;
        $schemaLine = '';

        if (is_array($schema)) {
            $schemaList = array_is_list($schema) ? $schema : [$schema];
            $schemaValues = [];

            foreach ($schemaList as $schemaEntry) {
                if (is_array($schemaEntry)) {
                    $schemaJson = json_encode(
                        $schemaEntry,
                        JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT,
                    );

                    if ($schemaJson !== false) {
                        $schemaValues[] = $schemaJson;
                    }

                    continue;
                }

                if (is_string($schemaEntry) && $schemaEntry !== '') {
                    $schemaValues[] = $schemaEntry;
                }
            }

            if ($schemaValues !== []) {
                $schemaLine = "\n                'meta_structure' => " . var_export($schemaValues, true) . ',';
            }
        }

        if (is_string($schema) && $schema !== '') {
            $schemaLine = "\n                'meta_structure' => " . var_export([$schema], true) . ',';
        }

        return "            [\n"
            . "                'url' => '{$entry['url']}',\n"
            . "                'meta_title' => '{$entry['meta_title']}',\n"
            . "                'meta_description' => '{$entry['meta_description']}',\n"
            . "                // 'og_image' => public_path('{$this->starterSeoOgImagePath($entry['url'])}'),"
            . $schemaLine
            . "\n            ],";
    }


    private function seoMigrationPath(): string
    {
        $existing = glob(
            database_path("migrations/*_create_site_seos_table.php"),
        );

        if (!empty($existing)) {
            return str_replace(base_path() . "/", "", $existing[0]);
        }

        $timestamp = new DateTimeImmutable()->format("Y_m_d_His");

        return "database/migrations/" .
            $timestamp .
            "_create_site_seos_table.php";
    }

    private function ensureSeoDependencies(bool $installDeps): bool
    {
        $dependencies = $this->seoDependencies();
        $missing = $this->missingPackages($dependencies);

        if (empty($missing)) {
            return true;
        }

        $requireList = array_map(
            fn(string $package) => $package . ":" . $dependencies[$package],
            $missing,
        );

        if (!$installDeps) {
            $this->warn(
                "Missing SEO dependencies. Re-run with --install-deps to install them.",
            );
            $this->line("composer require " . implode(" ", $requireList));
            $this->newLine();

            return false;
        }

        $this->info("Installing SEO dependencies...");

        if (! $this->runComposerRequirePackages($requireList)) {
            $this->error("Failed to install SEO dependencies.");

            return false;
        }

        $this->newLine();

        return true;
    }

    /**
     * @return array<string, string>
     */
    private function seoDependencies(): array
    {
        return [
            "filament/filament" => "^4.0",
            "spatie/laravel-medialibrary" => "^11.0",
            "filament/spatie-laravel-media-library-plugin" => "^4.0",
        ];
    }

    /**
     * @return array<string, class-string>
     */
    private function packageClassMap(): array
    {
        return [
            "filament/filament" => \Filament\Forms\Components\FileUpload::class,
            "spatie/laravel-medialibrary" =>
                \Spatie\MediaLibrary\HasMedia::class,
            "filament/spatie-laravel-media-library-plugin" =>
                \Filament\Forms\Components\SpatieMediaLibraryFileUpload::class,
            "spatie/laravel-tags" => \Spatie\Tags\HasTags::class,
        ];
    }

    /**
     * @param array<string, string> $dependencies
     * @return string[]
     */
    private function missingPackages(array $dependencies): array
    {
        $installed = $this->installedPackages();

        return array_values(array_filter(
            array_keys($dependencies),
            fn (string $package) => ! in_array($package, $installed, true),
        ));
    }

    /**
     * @return string[]
     */
    private function installedPackages(): array
    {
        if (! class_exists(\Composer\InstalledVersions::class)) {
            return array_keys((array) config('app.providers'));
        }

        return \Composer\InstalledVersions::getInstalledPackages();
    }

    /**
     * @param array<int, array<string, string|array>> $pageEntries
     */
    private function seedSeoEntries(array $pageEntries): void
    {
        if (!class_exists(\App\Models\SiteSeo::class)) {
            $this->warn(
                "SiteSeo model not found. Run migrations and re-run installer to seed SEO data.",
            );

            return;
        }

        try {
            foreach ($pageEntries as $entry) {
                $url = $entry["url"];
                $title = Str::headline(str_replace(".", " ", $entry["key"]));

                \App\Models\SiteSeo::query()->updateOrCreate(
                    ["url" => $url],
                    [
                        "meta_title" => $title,
                    ],
                );
            }
        } catch (\Throwable $exception) {
            $this->warn("Unable to seed SEO entries.");

            if (
                !$this->confirm("Run migrations now and retry seeding?", false)
            ) {
                return;
            }

            if (!$this->runMigrations()) {
                $this->error(
                    "Migration failed. Run migrations manually and re-run installer.",
                );

                return;
            }

            $this->newLine();

            $this->seedSeoEntries($pageEntries);
        }
    }

    private function ensureMediaLibrarySetup(): void
    {
        $configPath = config_path("media-library.php");

        if (!file_exists($configPath)) {
            if (
                $this->confirm(
                    "Publish Spatie Media Library config and migrations?",
                    true,
                )
            ) {
                $this->runArtisan([
                    "vendor:publish",
                    "--provider=Spatie\MediaLibrary\MediaLibraryServiceProvider",
                    "--tag=medialibrary-config",
                ]);
                $this->runArtisan([
                    "vendor:publish",
                    "--provider=Spatie\MediaLibrary\MediaLibraryServiceProvider",
                    "--tag=medialibrary-migrations",
                ]);
            }
        }
    }

    private function ensureTagsSetup(): void
    {
        $configPath = config_path('tags.php');

        if (! file_exists($configPath)) {
            if (! $this->confirm('Publish Spatie Tags config and migrations?', true)) {
                return;
            }

            $this->runArtisan([
                'vendor:publish',
                '--provider=Spatie\\Tags\\TagsServiceProvider',
                '--tag=tags-config',
            ]);

            $this->runArtisan([
                'vendor:publish',
                '--provider=Spatie\\Tags\\TagsServiceProvider',
                '--tag=tags-migrations',
            ]);
        }
    }

    private function ensureDeveloperLoginsPlugin(): void
    {
        if (! $this->confirm('Install Filament Developer Logins plugin?', true)) {
            return;
        }

        if (! $this->runComposerRequire('dutchcodingcompany/filament-developer-logins:^2.0')) {
            $this->error('Failed to install Filament Developer Logins plugin.');

            return;
        }

        $this->installDeveloperLoginsPlugin();
    }

    private function installDeveloperLoginsPlugin(): void
    {
        $providerPath = app_path('Providers/Filament/AdminPanelProvider.php');

        if (! file_exists($providerPath)) {
            $this->warn('Admin panel provider not found. Skipping developer logins registration.');

            return;
        }

        $contents = $this->filesystem()->get($providerPath);

        if (str_contains($contents, 'FilamentDeveloperLoginsPlugin')) {
            return;
        }

        if (! str_contains($contents, 'dutchcodingcompany/filament-developer-logins')) {
            $contents = str_replace(
                "use Filament\\Widgets\\FilamentInfoWidget;\n",
                "use Filament\\Widgets\\FilamentInfoWidget;\nuse DutchCodingCompany\\FilamentDeveloperLogins\\FilamentDeveloperLoginsPlugin;\n",
                $contents,
            );
        }

        $contents = str_replace(
            '->login()',
            "->login()\n            ->plugins([\n                FilamentDeveloperLoginsPlugin::make()\n                    ->enabled(app()->environment('local'))\n                    ->users(['Admin' => 'a@a.a']),\n            ])",
            $contents,
        );

        $this->filesystem()->put($providerPath, $contents);
    }

    private function runComposerRequire(string $package): bool
    {
        return $this->runComposerRequirePackages([$package]);
    }

    private function ensureFilamentPanel(): void
    {
        $providerPath = app_path("Providers/Filament/AdminPanelProvider.php");

        if (file_exists($providerPath)) {
            return;
        }

        if (
            ! $this->confirm(
                "Install Filament panel scaffolding for /admin?",
                true,
            )
        ) {
            return;
        }

        $this->runArtisan(["filament:install", "--panels", "--no-interaction"]);
    }

    private function ensureFilamentTheme(): void
    {
        $themePath = resource_path('css/filament/admin/theme.css');

        if (! file_exists($themePath)) {
            $this->runArtisan(['filament:make-theme', 'admin', '--no-interaction']);
        }

        if (! file_exists($themePath)) {
            $this->warn('Filament theme not found. Skipping rich editor styling.');

            return;
        }

        $contents = $this->filesystem()->get($themePath);
        $selector = $this->richEditorMinHeightSelector();

        if (Str::contains($contents, $selector)) {
            return;
        }

        $contents = rtrim($contents) . "\n\n" . $this->richEditorMinHeightStyles() . "\n";

        $this->filesystem()->put($themePath, $contents);
    }

    private function richEditorMinHeightSelector(): string
    {
        return '.fi-fo-rich-editor .fi-fo-rich-editor-content';
    }

    private function richEditorMinHeightStyles(): string
    {
        return $this->richEditorMinHeightSelector() . " {\n    min-height: 300px;\n}";
    }

    private function ensureBlogDependencies(bool $installDeps): bool
    {
        $dependencies = [
            'spatie/laravel-tags' => '^4.0',
            'spatie/laravel-medialibrary' => '^11.0',
            'filament/spatie-laravel-media-library-plugin' => '^4.0',
        ];

        return $this->ensureDependencies(
            'Blog',
            $dependencies,
            [
                'php artisan vendor:publish --provider="Spatie\\Tags\\TagsServiceProvider" --tag=tags-migrations',
                'php artisan vendor:publish --provider="Spatie\\MediaLibrary\\MediaLibraryServiceProvider" --tag=medialibrary-migrations',
                'php artisan migrate',
            ],
            $installDeps,
        );
    }

    private function ensureCareersDependencies(bool $installDeps): bool
    {
        $dependencies = [
            'spatie/laravel-medialibrary' => '^11.0',
            'filament/spatie-laravel-media-library-plugin' => '^4.0',
        ];

        return $this->ensureDependencies(
            'Careers (internal)',
            $dependencies,
            [
                'php artisan vendor:publish --provider="Spatie\\MediaLibrary\\MediaLibraryServiceProvider" --tag=medialibrary-migrations',
                'php artisan migrate',
            ],
            $installDeps,
        );
    }

    /**
     * @param array<string, string> $dependencies
     * @param string[] $extraSteps
     */
    private function ensureDependencies(string $label, array $dependencies, array $extraSteps, bool $installDeps): bool
    {
        $missing = $this->missingPackages($dependencies);

        if (empty($missing)) {
            return true;
        }

        $requireList = array_map(
            fn (string $package) => $package.':'.$dependencies[$package],
            $missing,
        );

        if (! $installDeps) {
            $this->warn('Missing '.$label.' dependencies. Re-run with --install-deps to install them.');
            $this->line('composer require '.implode(' ', $requireList));

            foreach ($extraSteps as $step) {
                $this->line($step);
            }

            $this->newLine();

            return false;
        }

        $this->info('Installing '.$label.' dependencies...');

        if (! $this->runComposerRequirePackages($requireList)) {
            $this->error('Failed to install '.$label.' dependencies.');

            return false;
        }

        $this->newLine();

        return true;
    }

    /**
     * @param string[] $requireList
     */
    private function runComposerRequirePackages(array $requireList): bool
    {
        $process = new Process(array_merge(
            ['composer', 'require', '--no-interaction', '--no-scripts'],
            $requireList,
        ));
        $process->setTty(Process::isTtySupported());
        $process->setTimeout(null);
        $process->run(function (string $type, string $buffer): void {
            $this->output->write($buffer);
        });

        if (! $process->isSuccessful()) {
            return false;
        }

        $this->pendingComposerScripts = true;
        $this->newLine();

        return true;
    }

    private function runPostComposerScripts(bool $runFilamentUpgrade): void
    {
        if (! $this->pendingComposerScripts) {
            return;
        }

        if (! $this->runArtisan(['package:discover', '--ansi'])) {
            $this->warn('Failed to run package discovery after installing dependencies.');

            return;
        }

        if ($runFilamentUpgrade && $this->shouldRunFilamentUpgrade()) {
            if (! $this->runArtisan(['filament:upgrade'])) {
                $this->warn('Failed to run Filament upgrade after installing dependencies.');
            }
        }

        $this->pendingComposerScripts = false;
    }

    private function shouldRunFilamentUpgrade(): bool
    {
        return in_array('filament/filament', $this->installedPackages(), true);
    }

    private function seedStarterUser(): void
    {
        $seederClass = '\\Database\\Seeders\\StarterUserSeeder';

        if (! class_exists($seederClass)) {
            $this->warn('Starter user seeder not found.');

            return;
        }

        if (! $this->confirm('Create starter admin user (a@a.a)?', true)) {
            return;
        }

        $this->runArtisan(['db:seed', '--class='.$seederClass, '--force']);
        $this->ensureDeveloperLoginsPlugin();
    }

    private function seedStarterSeo(): void
    {
        $seederClass = '\\Database\\Seeders\\StarterSeoSeeder';

        if (! class_exists($seederClass)) {
            $this->warn('Starter SEO seeder not found.');

            return;
        }

        if (! $this->confirm('Seed starter SEO entries now?', true)) {
            return;
        }

        if (! $this->runMigrations()) {
            $this->error('Migration failed. Run migrations manually and re-run installer.');

            return;
        }

        $this->runArtisan(['db:seed', '--class='.$seederClass, '--force']);
    }

    private function runMigrations(): bool
    {
        return $this->runArtisan(['migrate', '--force']);
    }

    /**
     * @param string[] $arguments
     */
    private function runArtisan(array $arguments): bool
    {
        $process = new Process(array_merge(["php", "artisan"], $arguments));
        $process->setTty(Process::isTtySupported());
        $process->setTimeout(null);
        $process->run(function (string $type, string $buffer): void {
            $this->output->write($buffer);
        });

        if (!$process->isSuccessful()) {
            return false;
        }

        $this->newLine();

        return true;
    }

    /**
     * @return array<string, string|bool>
     */
    private function planFile(
        Filesystem $files,
        array $manifest,
        string $relativePath,
        string $contents,
        bool $force,
        bool $allowMarker,
        bool $alwaysWrite,
    ): array {
        if ($relativePath === "routes/web.php") {
            return $this->planWebRoutes(
                $files,
                $manifest,
                $relativePath,
                $contents,
            );
        }

        if ($alwaysWrite) {
            return $this->planAlwaysWrite($files, $relativePath, $contents);
        }

        $absolutePath = base_path($relativePath);
        $exists = $files->exists($absolutePath);
        $hash = hash("sha256", $contents);

        $manifestFiles = Arr::get($manifest, "files", []);
        $manifestHash = is_array($manifestFiles)
            ? $manifestFiles[$relativePath] ?? null
            : null;
        $isManaged = is_string($manifestHash);

        $markerAllowed =
            $allowMarker && $this->hasMarker($files, $absolutePath);

        if ($exists && !$isManaged && !$force) {
            return [
                "path" => $relativePath,
                "status" => "skipped",
                "reason" => "conflict",
                "hash" => $hash,
                "contents" => $contents,
                "exists" => $exists,
            ];
        }

        if ($exists && !$isManaged && $force && !$markerAllowed) {
            return [
                "path" => $relativePath,
                "status" => "skipped",
                "reason" => "missing-marker",
                "hash" => $hash,
                "contents" => $contents,
                "exists" => $exists,
            ];
        }

        if (
            $exists &&
            $isManaged &&
            $manifestHash === $hash &&
            $files->get($absolutePath) === $contents
        ) {
            return [
                "path" => $relativePath,
                "status" => "unchanged",
                "hash" => $hash,
                "contents" => $contents,
                "exists" => $exists,
            ];
        }

        return [
            "path" => $relativePath,
            "status" => $exists ? "update" : "create",
            "hash" => $hash,
            "contents" => $contents,
            "exists" => $exists,
        ];
    }

    /**
     * @return array<string, string|bool>
     */
    private function planWebRoutes(
        Filesystem $files,
        array $manifest,
        string $relativePath,
        string $contents,
    ): array {
        $absolutePath = base_path($relativePath);
        $exists = $files->exists($absolutePath);
        $hash = hash("sha256", $contents);

        if (!$exists) {
            return [
                "path" => $relativePath,
                "status" => "create",
                "hash" => $hash,
                "contents" => $contents,
                "exists" => $exists,
                "always_update" => true,
            ];
        }

        if ($files->get($absolutePath) === $contents) {
            return [
                "path" => $relativePath,
                "status" => "unchanged",
                "hash" => $hash,
                "contents" => $contents,
                "exists" => $exists,
                "always_update" => true,
            ];
        }

        return [
            "path" => $relativePath,
            "status" => "update",
            "hash" => $hash,
            "contents" => $contents,
            "exists" => $exists,
            "always_update" => true,
        ];
    }

    /**
     * @return array<string, string|bool>
     */
    private function planAlwaysWrite(
        Filesystem $files,
        string $relativePath,
        string $contents,
    ): array {
        $absolutePath = base_path($relativePath);
        $exists = $files->exists($absolutePath);
        $hash = hash("sha256", $contents);

        if ($exists && $files->get($absolutePath) === $contents) {
            return [
                "path" => $relativePath,
                "status" => "unchanged",
                "hash" => $hash,
                "contents" => $contents,
                "exists" => $exists,
            ];
        }

        return [
            "path" => $relativePath,
            "status" => $exists ? "update" : "create",
            "hash" => $hash,
            "contents" => $contents,
            "exists" => $exists,
        ];
    }

    /**
     * @param array<int, array<string, string|bool>> $plan
     * @return array<string, array<string>>
     */
    private function summarizePlan(array $plan): array
    {
        $summary = [
            "create" => [],
            "update" => [],
            "unchanged" => [],
            "skipped" => [],
        ];

        foreach ($plan as $item) {
            $status = $item["status"];

            if (!is_string($status) || !array_key_exists($status, $summary)) {
                continue;
            }

            $summary[$status][] = $item["path"];
        }

        return $summary;
    }

    /**
     * @param array<string, array<string>> $summary
     */
    private function displayPlanSummary(array $summary): void
    {
        foreach (
            [
                "create" => "Will create",
                "update" => "Will update",
                "unchanged" => "Unchanged",
                "skipped" => "Skipped",
            ]
            as $key => $label
        ) {
            $items = $summary[$key] ?? [];

            if (empty($items)) {
                continue;
            }

            $this->line($label . ":");
            foreach ($items as $path) {
                $this->line("  - " . $path);
            }
            $this->newLine();
        }
    }

    /**
     * @param array<int, array<string, string|bool>> $plan
     * @return array{written_files: array<string, string>, skipped: array<string, string>}
     */
    private function applyPlan(Filesystem $files, array $plan): array
    {
        $writtenFiles = [];
        $skipped = [];

        foreach ($plan as $item) {
            $status = $item["status"] ?? "skipped";
            $path = $item["path"];
            $contents = $item["contents"];
            $hash = $item["hash"];

            if (
                !is_string($path) ||
                !is_string($contents) ||
                !is_string($hash)
            ) {
                continue;
            }

            if (!in_array($status, ["create", "update"], true)) {
                if ($status === "skipped") {
                    $skipped[$path] = (string) ($item["reason"] ?? $status);
                }

                continue;
            }

            $absolutePath = base_path($path);
            $directory = dirname($absolutePath);

            if (!$files->isDirectory($directory)) {
                $files->makeDirectory($directory, 0755, true);
            }

            $files->put($absolutePath, $contents);
            $writtenFiles[$path] = $hash;
        }

        return [
            "written_files" => $writtenFiles,
            "skipped" => $skipped,
        ];
    }

    /**
     * @param array<int, array<string, string|array>> $pageEntries
     * @param array<string, string> $writtenFiles
     */
    private function writeManifest(
        array $pageEntries,
        array $writtenFiles,
        array $skipped,
    ): void {
        $filesystem = $this->filesystem();
        $manifestPath = $this->manifestPath();
        $directory = dirname($manifestPath);
        $existingManifest = $filesystem->exists($manifestPath)
            ? $filesystem->get($manifestPath)
            : null;

        if (!$filesystem->isDirectory($directory)) {
            $filesystem->makeDirectory($directory, 0755, true);
        }

        $manifest = [
            "package" => config("starter.package_name"),
            "version" => config("starter.version"),
            "generated_at" => new DateTimeImmutable()->format(
                DateTimeImmutable::ATOM,
            ),
            "pages" => collect($pageEntries)
                ->map(fn(array $entry) => implode(">", $entry["segments"]))
                ->all(),
            "files" => $this->mergeManifestFiles(
                $writtenFiles,
                $skipped,
                $existingManifest,
            ),
        ];

        $filesystem->put(
            $manifestPath,
            json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) .
                "\n",
        );
    }

    private function renderStub(string $path, array $replacements): string
    {
        $contents = $this->filesystem()->get($path);

        foreach ($replacements as $key => $value) {
            $contents = str_replace("{{ " . $key . " }}", $value, $contents);
        }

        return $contents;
    }

    /**
     * @param array<string, string> $writtenFiles
     * @param array<string, string> $skipped
     */
    private function mergeManifestFiles(
        array $writtenFiles,
        array $skipped,
        ?string $existingManifest,
    ): array {
        $existingFiles = [];

        if (is_string($existingManifest)) {
            $decoded = json_decode($existingManifest, true);
            $existingFiles = is_array($decoded)
                ? Arr::get($decoded, "files", []) ?? []
                : [];
        }

        if (!is_array($existingFiles)) {
            $existingFiles = [];
        }

        $keptFromExisting = Arr::except($existingFiles, array_keys($skipped));
        $keptFromExisting = Arr::except(
            $keptFromExisting,
            array_keys($writtenFiles),
        );

        return array_merge($keptFromExisting, $writtenFiles);
    }

    private function stubPath(string $path): string
    {
        return dirname(__DIR__, 2) . "/stubs/" . $path;
    }

    private function manifestPath(): string
    {
        return config("starter.manifest_path");
    }

    private function hasMarker(Filesystem $files, string $path): bool
    {
        if (!$files->exists($path)) {
            return false;
        }

        $contents = $files->get($path);

        return Str::contains($contents, "Generated by Starter Package");
    }

    private function filesystem(): Filesystem
    {
        if (!$this->filesystem instanceof Filesystem) {
            $this->filesystem = app(Filesystem::class);
        }

        return $this->filesystem;
    }
}
